PYTHONPATH=. python main.py \
--schema-path data/bookhatball-schema.json \
--train-examples-paths scr/data/train-parsed.json \
--test-examples-paths scr/data/val-parsed.json \
--model lf2lf \
--model-path checkpoint/lf2lf \
--mappings mappings/lf2lf \
--word-vec-size 200 \
--pretrained-wordvec '' '' \
--kb-embed-size 200 \
--rnn-size 200 --rnn-type LSTM --global-attention multibank_general \
--enc-layers 2 --dec-layers 2 \
--num-context 2 \
--batch-size 128 --gpuid 0 --optim adagrad --learning-rate 0.01 \
--epochs 15 --report-every 500 \
--cache cache/lf2lf \
--verbose --ignore-cache
